# you can put a URL here which players can use to appeal for being unbanned
ban-appeal-url: ''

# set to 'true' if you want to allow connecting while BanMod is experiencing a downtime, e.g. through a database downtime
allow-unsafe-connections: false
