banmod:
  database:
    type: h2 # h2 or MySQL
    url: jdbc:h2:file:./banmod.h2 # default is a local h2 database
    username: sa
    password:
  entity_service: database # database or file
  banAppealUrl: '' # you can put a URL here which players can use to appeal for being unbanned
