name: BanMod
version: '0.1.0'
author: Kaleidox
description: Cross-Server Punishment modification
website: https://github.com/AMPZNetwork/BanMod
main: com.ampznetwork.banmod.spigot.BanMod$Spigot
default-permission: op
api-version: '1.18'
database: true
load: STARTUP
depend:
  - LibMod
softdepend:
  - LuckPerms
permissions:
  banmod.bypass:
    description: A tree of permission nodes to bypass certain punishments
    children:
      banmod.bypass.kick:
        description: /kick has no effect on you
      banmod.bypass.mute:
        description: /mute and /tempmute have no effect on you
      banmod.bypass.ban:
        description: /ban and /tempban have no effect on you
  banmod.notify:
    description: A tree of permission nodes to control notifications in the
    children:
      banmod.notify.kick:
        description: Get notified when someone gets kicked
      banmod.notify.mute:
        description: Get notified when someone gets muted
      banmod.notify.ban:
        description: Get notified when someone gets banned
      banmod.notify.error:
        default: false
        description: Get notified when the plugin gets a fatal error
commands:
  reload:
    description: Reloads Configuration Files
    permission: banmod.reload
  cleanup:
    description: Cleanup Database
    permission: banmod.cleanup
  lookup:
    description: Lookup User Entry
    permission: banmod.lookup
  punish:
    description: Punish User
    permission: banmod.punish
  mutelist:
    description: Mute User
    permission: banmod.mutelist
  tempmute:
    description: Temporarily Mute User
    permission: banmod.tempmute
  mute:
    description: Mute User
    permission: banmod.mute
  unmute:
    description: Unmute User
    permission: banmod.unmute
  kick:
    description: Kick User
    permission: banmod.kick
  banlist:
    description: Lookup User Entry
    permission: banmod.banlist
  tempban:
    description: Temporarily Ban User
    permission: banmod.tempban
  ban:
    description: Ban User
    permission: banmod.ban
  unban:
    description: Unban User
    permission: banmod.unban
  infraction:
    aliases: punishment
    description: Interact with and manage Infractions
    permission: banmod.infraction
  category:
    description: Modify Punishment Categories
    permission: banmod.category
  import:
    description: Import Data from other sources
    permission: banmod.import
