name: BanMod
version: '0.1.0'
description: Cross-Server Punishment modification
main: com.ampznetwork.banmod.spigot.BanMod$Spigot
api-version: '1.18'
load: STARTUP
website: https://github.com/AMPZNetwork/BanMod
commands:
  reload:
    description: Reloads Configuration Files
    permission: banmod.reload
  category:
    description: Modify Punishment Categories
    permission: banmod.category
  lookup:
    description: Lookup User Entry
    permission: banmod.lookup
  punish:
    description: Punish User
    permission: banmod.punish
  tempmute:
    description: Temporarily Mute User
    permission: banmod.tempmute
  mute:
    description: Mute User
    permission: banmod.mute
  unmute:
    description: Unmute User
    permission: banmod.unmute
  kick:
    description: Kick User
    permission: banmod.kick
  tempban:
    description: Temporarily Ban User
    permission: banmod.tempban
  ban:
    description: Ban User
    permission: banmod.ban
  unban:
    description: Unban User
    permission: banmod.unban
