name: BanMod
version: '0.1.0'
author: Kaleidox
description: Cross-Server Punishment modification
website: https://github.com/AMPZNetwork/BanMod
main: com.ampznetwork.banmod.spigot.BanMod$Spigot
default-permission: op
api-version: '1.18'
database: true
load: STARTUP
depend:
  - LibMod
softdepend:
  - LuckPerms
commands:
  reload:
    description: Reloads Configuration Files
    permission: banmod.reload
  cleanup:
    description: Cleanup Database
    permission: banmod.cleanup
  lookup:
    description: Lookup User Entry
    permission: banmod.lookup
  punish:
    description: Punish User
    permission: banmod.punish
  mutelist:
    description: Mute User
    permission: banmod.mutelist
  tempmute:
    description: Temporarily Mute User
    permission: banmod.tempmute
  mute:
    description: Mute User
    permission: banmod.mute
  unmute:
    description: Unmute User
    permission: banmod.unmute
  kick:
    description: Kick User
    permission: banmod.kick
  banlist:
    description: Lookup User Entry
    permission: banmod.banlist
  tempban:
    description: Temporarily Ban User
    permission: banmod.tempban
  ban:
    description: Ban User
    permission: banmod.ban
  unban:
    description: Unban User
    permission: banmod.unban
  infraction:
    aliases: punishment
    description: Interact with and manage Infractions
    permission: banmod.infraction
  category:
    description: Modify Punishment Categories
    permission: banmod.category
  import:
    description: Import Data from other sources
permissions:
  banmod:
    description: Root permission node
    default: false
    children:
      banmod.reload:
        description: Permission for the /banmod:reload command
        default: op
      banmod.cleanup:
        description: Permission for the /banmod:cleanup command
        default: op
      banmod.lookup:
        description: Permission for the /banmod:lookup command
        default: op
      banmod.punish:
        description: Permission for the /banmod:punish command
        default: op
      banmod.mutelist:
        description: Permission for the /banmod:mutelist command
        default: op
      banmod.tempmute:
        description: Permission for the /banmod:tempmute command
        default: op
      banmod.mute:
        description: Permission for the /banmod:mute command
        default: op
      banmod.unmute:
        description: Permission for the /banmod:unmute command
        default: op
      banmod.kick:
        description: Permission for the /banmod:kick command
        default: op
      banmod.banlist:
        description: Permission for the /banmod:banlist command
        default: op
      banmod.tempban:
        description: Permission for the /banmod:tempban command
        default: op
      banmod.ban:
        description: Permission for the /banmod:ban command
        default: op
      banmod.unban:
        description: Permission for the /banmod:unban command
        default: op
      banmod.category:
        description: Permission for the /banmod:category command
        default: op
      banmod.infraction:
        description: Permission for the /banmod:infraction command
        default: op
      banmod.bypass:
        description: A tree of permission nodes to bypass certain punishments
        children:
          banmod.bypass.kick:
            description: /kick has no effect on you
            default: op
          banmod.bypass.mute:
            description: /mute and /tempmute have no effect on you
            default: op
          banmod.bypass.ban:
            description: /ban and /tempban have no effect on you
            default: op
      banmod.notify:
        description: A tree of permission nodes to control notifications in the
        children:
          banmod.notify.kick:
            description: Get notified when someone gets kicked
            default: op
          banmod.notify.mute:
            description: Get notified when someone gets muted
            default: op
          banmod.notify.ban:
            description: Get notified when someone gets banned
            default: op
          banmod.notify.error:
            description: Get notified when the plugin gets a fatal error
            default: op
